### ISSUE TITLE
Generate and Send PDF

### ISSUE THREAD

**Issue by verschoof** [psliwa/PdfBundle#18]
Hi there,

I want to create a PDF file on the file and send it directly to somebody's mail.
I'm using PDFBundle and Swiftmailer.
But I don't know how I can do this...

Can somebody help me?

Regards, Mitchel

**Comment by prakashsinghgaur** [comment]
Can you give some snnipet to save this content into a pdf file on server. @verschoof @psliwa

**Comment by Zoopme** [comment]
@verschoof please note that `newInstance()` methods have been removed with SwiftMailer 6.0.0 release (see [swiftmailer/CHANGES at master · swiftmailer/swiftmailer](https://github.com/swiftmailer/swiftmailer/blob/master/CHANGES))

You should now use :
`-> attach(new \Swift_Attachment($pdf, 'Huurovereenkomst.pdf', 'application/pdf'))`
