### ISSUE TITLE
Twig_Function_Method is deprecated in Symfony 2.3.32

### ISSUE THREAD

**Issue by tuanquynh0508** [psliwa/PdfBundle#60]
Using an instance of "Twig_Function_Method" for function "pdf_image" is deprecated. Use Twig_SimpleFunction instead.

I use Symfony version 2.3.32

**Comment by psliwa** [comment]
I think this is the same issue as #59. I will take care of this soon.

**Comment by tuanquynh0508** [comment]
Great. Thank you very much!
