### ISSUE TITLE
factory-service attribute deprecated

### ISSUE THREAD

**Issue by doppynl** [psliwa/PdfBundle#61]
Symfony is issuing deprecated messages because of the way a couple of services are defined. 

The messages are as followed:

	DEPRECATED - Symfony\Component\DependencyInjection\Definition::setFactoryMethod(build) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead

	DEPRECATED - The "factory-service" attribute of service "ps_pdf.facade" in file "--local-dir--/var/cache/dev/appDevDebugProjectContainer.xml" is deprecated since version 2.6 and will be removed in 3.0. Use the "factory" element instead.

This is for services named `ps_pdf.facade` and `ps_pdf.facade_builder`.

Resolution for this is to use the element `factory` instead of the attributes.
See the symfony documentation for more details: http://symfony.com/doc/2.6/components/dependency_injection/factories.html

Fixing this will require changing the minimum requirement of symfony to (at least) 2.6.
Leaving it as is will become problematic for developers wanting to use symfony 3.0.

I can create a pull request for these changes, but that would also include bumping the required version of symfony to ~2.6 (and adding ~3.0).

**Comment by Soullivaneuh** [comment]
> I can create a pull request for these changes, but that would also include bumping the required version of symfony to ~2.6 (and adding ~3.0).

2.3 is still maintained. BC can and should be handled.

**Comment by doppynl** [comment]
2.3 is indeed still maintained.

Issue for me is, how do I keep 2.3 AND 3.0 working when the problem is with a service definition in xml?
Do I create 2 different xml-files and check the version of Symfony in the Extension class and load the appropiate one? 

Do I replace the new definition with a backwards-compatible one in the extension class after loading the new xml-file?

**Comment by Soullivaneuh** [comment]
By defining them manually on the bundle extension.

See this PR as example: https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/pull/306/files
